pipeline {
  agent any
 // tools {
   //   terraform "Terraform1.0.0"
  //}

  stages {
    stage('Git Checkout') 

    {
      steps {
      checkout scm
    }
    }
    
    stage('relocate') {
      
      steps {
           dir('K8S-TF'){
              bat "${tool name: 'Terraform'}\terraform --version"
        bat label: '', script: 'terraform init'
           }
      }
    
    }
  //  stage('Terraform Init') {
      
    //  steps {
           
      //  bat label: '', script: 'terraform init'
      //}
    
   // }
    
   // stage('Terraform apply') {
     // steps {
       // bat label: '', script: 'terraform apply --auto-approve'
      //}
   // }
  }
}