node{
def app
 stage('Clone repository') {

        checkout scm
    
 }

 stage('Scan My Source Code') {
   
      script
      {
        bat 'cd GIT-JEN-FortiDevSec'
        bat 'docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest'
        bat 'docker run --rm --mount type=bind,source=C:/ProgramData/Jenkins/.jenkins/workspace/FTNT/GIT-JEN-FortiDevSec,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest'       
            
        }     
           
      }         
    
  }





