node{
def app
 stage('Clone repository') {

        checkout scm
    
 }

 stage('Shell script 0') {
   
      script
      {
         bat 'cd GIT-JEN-ACR'
        bat 'docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest'
        bat 'docker run --rm --mount type=bind,source=C:/ProgramData/Jenkins/.jenkins/workspace/FTNT/GIT-JEN-ACR,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest'       
            
        }     
           
      }         
    
  }





