pipeline {
   agent any
stages{
 stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */
steps{
        checkout scm
    }
 }

 stage('Shell script 0') {
   
      steps {

         sh 'GIT-JEN-ACR'
         
        sh '''env | grep -E "JENKINS_HOME|BUILD_ID|GIT_BRANCH|GIT_COMMIT" > /tmp/env
docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest'''
      
      }
    }
  }
}

