pipeline {
   agent any
stages{
 stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */
steps{
        checkout scm
    }
 }

 stage('Shell script 0') {
   
      steps {

         bat 'cd GIT-JEN-ACR'
         
       
      }
    }
  }
}

